### ISSUE TITLE
chiaki doesn't work

### ISSUE THREAD

**Issue by Ronald-Diemicke** [uureel/batocera.pro#1]
Getting the following error when running the install:

curl -L chiaki.batocera.pro | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   162  100   162    0     0    652      0 --:--:-- --:--:-- --:--:--   650
bash: line 8: syntax error near unexpected token `newline'
bash: line 8: `<!DOCTYPE html>'
100 12321    0 12321    0     0  16428      0 --:--:-- --:--:-- --:--:-- 16428
curl: (23) Failure writing output to destination

**Comment by uureel** [comment]
@Ronald-Diemicke should be fixed, tested & working here, test please and lmk

**Comment by Ronald-Diemicke** [comment]
Yup tested and good! 
Thank you!
