### ISSUE TITLE
Is it possible to add 3DSen Linux to Batocera Pro Apps?

### ISSUE THREAD

**Issue by Sleyk2010** [uureel/batocera.pro#12]
Hey there! Can you add 3DSen (there's supposed to be a Linux version) to your unofficial apps? I purchased it, but I don't see the option to install it for Linux. 

I am gladly giving you a copy to add to the unofficial apps, as I can't figure out how to implement it. It has an executable .exe, but no familiar Linux folders, so I want to send you a copy to make sense of it. I uploaded it to my Internet Archive storage for easy downloading for you as the zip file size is 77MB, and Github wont let me attach anything over 25MB.

I also included 84 of the latest working roms for it. Would be awesome if you can include this with the unofficial apps for Batocera, and allow it to be installed in Ports like the other apps! Please see link below!

Thank you! 

https://archive.org/details/3d-sen-0.97-latest-with-roms

**Comment by uureel** [comment]
hi, afaict you should be able to use it via steam/flatpak
