### ISSUE TITLE
access TRANSMISSION File

### ISSUE THREAD

**Issue by MYLE-01** [uureel/batocera.pro#13]
Works allsum THANKS

only one problem

can't find the files after press f1

they are setting in the Downloads folder

what am I missing 

thanks Again

**Comment by uureel** [comment]
it's a windows/wine/lutris app, so you're looking for 
/userdata/saves/lutris/proton/transmission-qt.exe.wine/drive_c/users/steamuser/Downloads/
(this path might differ depending on batocera version)

**Comment by MYLE-01** [comment]
Thanks Bro Found them
