### ISSUE TITLE
Error with sunshine

### ISSUE THREAD

**Issue by WoodySlum** [uureel/batocera.pro#14]
While running sunshine, I've got the following error : 

```
/tmp/.mount_sunshiRfRbhw/usr/bin/sunshine: error while loading shared libraries: libsystemd.so.0: cannot open shared object file: No such file or directory
```

It worked well for a while but I would like to test the latest update. If I'm not wrong, systemd is not installed in batocera ...

Thank you for your work

**Comment by uureel** [comment]
can you confirm this happens with the latest version/update? (to update just run the curl installer again) 

❯ md5sum ~/pro/sunshine/batocera-sunshine
90d89622af94c4da7f58362b2a11e8a2  /userdata/system/pro/sunshine/batocera-sunshine

**Comment by WoodySlum** [comment]
Yes. I was previously using a version installed in May or June.

```
[root@BATOCERA /userdata/system/pro/sunshine]# md5sum ~/pro/sunshine/batocera-sunshine
90d89622af94c4da7f58362b2a11e8a2  /userdata/system/pro/sunshine/batocera-sunshine
```

**Comment by uureel** [comment]
which batocera version are you on?

**Comment by WoodySlum** [comment]
Batocera 37c 👍

**Comment by uureel** [comment]
should be fixed, tested fine on 37 and 38 with hw accel working on intel and nvidia; test and lmk  

[root@BATOCERA /userdata/system/pro/sunshine]# md5sum batocera-sunshine
294a77e64cfe37d7364d2d6428c5fc43  batocera-sunshine

**Comment by WoodySlum** [comment]
Thanks for the quick fix !

It works well great !

The only strange thing is I have to restart process when the computer boots (`pro/sunshine/batocera-sunshine restart`)

**Comment by uureel** [comment]
i changed the startup delay to shorter that's probably the cause, edit ~/pro/sunshine/extras/startup.sh and change sleep 22 to sleep 33 and lmk if that works

**Comment by WoodySlum** [comment]
That works nice 33 seconds ! Thanks a lot !

**Comment by WoodySlum** [comment]
Hi, apologized for this but even with increasing delay, I have randomly (but very often) the followinf error now : 

```
/tmp/.mount_sunshiS2Ona3/usr/bin/sunshine: /usr/lib/libcurl.so.4: no version information available (required by /tmp/.mount_sunshiS2Ona3/usr/bin/sunshine)
/tmp/.mount_sunshiS2Ona3/AppRun: line 109:  3035 Segmentation fault      "$SUNSHINE_BIN_HERE" $@
````

Do you have also this ?

**Comment by uureel** [comment]
yep, was a total mess, thx for testing; 

seems to be fixed now; 
ran a bunch of tests fine on 37/38 @ intel & nv, delay increased to 44, sunshine will now also autorespawn in case it errors/drops for whatever reason 

`[root@BATOCERA /userdata/system/pro/sunshine]# md5sum ./batocera-sunshine
546656fa0192de99c33bdf032521c5c1  ./batocera-sunshine`

**Comment by WoodySlum** [comment]
Thanks a lot for the quick fix ! Tested with 4 reboots  (amd radeon) and works well !

Sebastien

**Comment by WoodySlum** [comment]
Hey @uureel,

I have a new issue with sunshine 0.21
When running the script, it's neverend : 

```
██  batocera.pro sunshine installer 

  
██  downloading sunshine.AppImage
    from > github.com/LizardByte/Sunshine/releases/download/nightly-dev/sunshine.AppImage
    to   > /userdata/system/pro/sunshine/sunshine.AppImage
######################################################################## 100.0%
    done, 52 MB

  
██  downloading batocera-sunshine
    from > batocera.pro/app/batocera-sunshine.AppImage
    to   > /userdata/system/pro/sunshine/batocera-sunshine
######################################################################## 100.0%
    done, 265 MB

  
██  downloading additional 22 files 
    done, 2 MB

  
██  installing
    done 
```

And when I start sunshine : 

```
[root@BATOCERA /userdata/system/pro/sunshine]# /userdata/system/pro/sunshine/batocera-sunshine restart
Something went wrong trying to read the squashfs image.

Cannot mount AppImage, please check your FUSE setup.
You might still be able to extract the contents of this AppImage 
if you run it with the --appimage-extract option. 
See https://github.com/AppImage/AppImageKit/wiki/FUSE 
for more information
open dir error: No such file or directory
[root@BATOCERA /userdata/system/pro/sunshine]# 
```

Do you also have the issue ?

Sebastien

**Comment by uureel** [comment]
i've just been uploading an updated 0.21 version, so you might've pulled a partial upload (should be 288mb not 265); 
![image](https://github.com/uureel/batocera.pro/assets/116395185/e4011ac8-9f85-4506-832e-e54a7c15ffad)

anyway it works fine here - try the installer again; 
also, if you remove ~/pro/sunshine/sunshine.AppImage and/or ~/sunshine/sunshine.AppImage it'll use the included 0.21 version automatically, otherwise you can also use those locations to run any mainline/dev sunshien version w/o updating batocera-sunshine

**Comment by WoodySlum** [comment]
Thank you for the fast feedback :)

Does it starts for you ?

I have those errors : 
```
/tmp/.mount_sunshiKdt147/usr/bin/sunshine: /lib/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /tmp/.mount_batoceCkNFNL/lib/libkrb5.so.26)
/tmp/.mount_sunshiKdt147/usr/bin/sunshine: /lib/libcrypt.so.1: version `XCRYPT_2.0' not found (required by /tmp/.mount_batoceCkNFNL/lib/libroken.so.18)
```

```
[root@BATOCERA /userdata/system]# md5sum pro/sunshine/batocera-sunshine 
327ac0f5888b910db6ac338f20f11d2a  pro/sunshine/batocera-sunshine
[root@BATOCERA /userdata/system]# 
```

**Comment by WoodySlum** [comment]
Nope I have migrate on v38 `OS version: 38c 2023/10/14 21:43` 

here is my lib checksum 

```
[root@BATOCERA /userdata/system]# md5sum /lib/libcrypt.so.1
7afb87549f0d095f5bb0a028e9e0936e  /lib/libcrypt.so.1
```

**Comment by uureel** [comment]
added libcrypt to the package; lmk if it works 

❯ md5sum ./batocera-sunshine.AppImage
8d278b7a62152068e6254cd07fb4ca5c  ./batocera-sunshine.AppImage

**Comment by WoodySlum** [comment]
You're the boss ! Works now thank you for your time and your effort !

Just a last question, when starting the web GUI, I can see this : 

```
Version 0.20.0

A new Stable Version is Available!
```

Same for you ?

Thanks again

**Comment by uureel** [comment]
it does include 0.21 but it doesn't overwrite existing versions, 

gotta remove manually 
~/pro/sunshine/sunshine.AppImage 
~/sunshine/sunshine.AppImage 

likewise you can place any version eg nightly/dev, there

**Comment by uureel** [comment]
it shows which version/location it's using when run from commandline 
![image](https://github.com/uureel/batocera.pro/assets/116395185/b9af6cde-b7f6-4c31-91f8-d715d5f3dcd2)

**Comment by WoodySlum** [comment]
yes perfect I have the latest version now. Thank you again !

Sebastien
