### ISSUE TITLE
How to run apps in the background

### ISSUE THREAD

**Issue by sudo-nitz** [uureel/batocera.pro#16]
Hi!

I've a question about autostarting up apps in minimized window. I've have downloaded Transmission and edited script custom.sh:

```
#!/bin/bash
/userdata/system/pro/transmission/extra/startup &
/userdata/system/pro/transmission/Launcher &
```

In launcher we can find:

```
#!/bin/bash 
unclutter-remote -s
DISPLAY=:0.0 batocera-wine lutris play /userdata/system/pro/transmission/transmission-qt.exe 2>/dev/null
```

How to run apps in the background?

**Comment by uureel** [comment]
start them from f1 and use alt+tab, ports are blocking multitasking
