### ISSUE TITLE
cockatrice won't start

### ISSUE THREAD

**Issue by palmerj** [uureel/batocera.pro#19]
DISPLAY=:0.0 QT_SCALE_FACTOR="1.25" GDK_SCALE="1.25" batocera-wine lutris play /userdata/system/pro/cockatrice/cockatrice.exe
Remove Symblink
Creating links on /userdata, Linux File System required !!!
fsync: up and running.
wine: Using setpriority to control niceness in the [-19,19] range
Application could not be started, or no application associated with the specified file.
ShellExecuteEx failed: File not found.

running butterfly v39

**Comment by trashbus99** [comment]
Are you using NTFS or ExFAT?  Wine usually needs EXT4 or BTRFS to work and the error log suggests you aren't using them.

**Comment by trashbus99** [comment]
> DISPLAY=:0.0 QT_SCALE_FACTOR="1.25" GDK_SCALE="1.25" batocera-wine lutris play /userdata/system/pro/cockatrice/cockatrice.exe Remove Symblink Creating links on /userdata, Linux File System required !!! fsync: up and running. wine: Using setpriority to control niceness in the [-19,19] range Application could not be started, or no application associated with the specified file. ShellExecuteEx failed: File not found.
> 
> running butterfly v39

Are you using NTFS or ExFAT? Wine usually needs EXT4 or BTRFS to work and the error log suggests you aren't using them.

**Comment by uureel** [comment]
@palmerj not sure where that /trice/trice/trice.exe is from
the installer does `echo 'DISPLAY=:0.0 batocera-wine windows play /userdata/system/pro/cockatrice/cockatrice.exe' >> $launcher`

can confirm it works fine on v38, but if bato breaks wine apps all again with v39, can't help

**Comment by uureel** [comment]
@palmerj managed to get native ubuntu deb version 2.9 working, run the installer again to update 
![image](https://github.com/uureel/batocera.pro/assets/116395185/79852af5-b73f-4f06-88e2-9061bab754fb)

**Comment by uureel** [comment]
@palmerj fixed

**Comment by uureel** [comment]
updated, should be adding to ports too or you can put any app there manually by copying the launcher from pro/app to roms/ports/app.sh
