### ISSUE TITLE
xcloud exit

### ISSUE THREAD

**Issue by isilkin** [uureel/batocera.pro#27]
Hello, first of all I would like to thank whoever is managing this repo. I hope it will always be there and stay up to date. 
xcloud does not seem to respond to the exit combo on the controller start+select. Even if I try to press the guide button and go to the "X" in the top right to exit the browser noting happens. Same happens if I use a keyboard or mouse.
Thank you.

**Comment by EduSouza-programmer** [comment]
I noticed the same thing, to exit I didn't use the hotkey, I used alt+f4 and everything worked fine.

**Comment by trashbus99** [comment]
> Hello, first of all I would like to thank whoever is managing this repo. I hope it will always be there and stay up to date. xcloud does not seem to respond to the exit combo on the controller start+select. Even if I try to press the guide button and go to the "X" in the top right to exit the browser noting happens. Same happens if I use a keyboard or mouse. Thank you.

use pad2key in advanced game settings to map alt-f4 to hotkey+start

**Comment by uureel** [comment]
added default hotkey+start = alt+f4 ports launcher padtokey to the installer 
@isilkin @EduSouza-programmer @trashbus99
