### ISSUE TITLE
Youtube TV - Old build detected

### ISSUE THREAD

**Issue by isilkin** [uureel/batocera.pro#28]
When launching YoutubeTV app "old build detected" error message appears. 
![IMG20240214103641](https://github.com/uureel/batocera.pro/assets/45017079/1025852d-8e1a-4b26-89b4-1408484796ff)

**Comment by uureel** [comment]
run the installer again or use this command: 
`sed -i "s,!appArgs.disableOldBuildWarning,1 == 0,g" /userdata/system/pro/youtubetv/resources/app/lib/main.js`

**Comment by isilkin** [comment]
I can confirm the issue is fixed. Thank you so much.
