### ISSUE TITLE
Adding portproton

### ISSUE THREAD

**Issue by isilkin** [uureel/batocera.pro#31]
I am not sure if this is the right place to post this.
Have you thought about adding portproton to the list. It's like lutris but more automated, more powerful and has constant updates. Here is the link
https://github.com/Castro-Fidel/PortWINE

What about some of the biggest streaming services like Netflix or Hulu etc. so batocera is more of a console experience.

**Comment by uureel** [comment]
added portproton to the steam container, hulu+netflix added both to the steam container and as standalone apps

**Comment by isilkin** [comment]
I think you are a rockstar. I wanted to test those new apps but you must have changed something because now none of the apps in the arch container are launching. 
If you launch any app it just exits.
I am on a clean install on v38. Here are some screenshots.
![IMG20240224144041](https://github.com/uureel/batocera.pro/assets/45017079/e656253f-da49-4edd-b3bc-30132a1e5cfe)
![IMG20240224144046](https://github.com/uureel/batocera.pro/assets/45017079/73d3e589-7cbc-4c86-97b7-4df63cbb73e3)

**Comment by isilkin** [comment]
Nevermind, it must be my user error. If you install lutris  and choose option 1 on the next screen then all apps will work correctly.
