### ISSUE TITLE
Firefox cannot download any files & forced to full screen

### ISSUE THREAD

**Issue by batoceragaming** [uureel/batocera.pro#32]
Hi, Thanks for this awesome app package.

Finally I can browse the internet in Batocera by installing Firefox from batocera.pro

However I have two main issues:
1. I cannot save/download any files or images to the directory
2. Whenever I opened the firefox, it is always forced to open in full screen. Is there a way to make it like a normal firefox that is not in full screen?

Many thanks for your answer.

**Comment by uureel** [comment]
run the installer to update it to the latest available version, 

1. it downloads fine into the folder specified in the settings (but opens /userdata to 'show downloads' instead (while they by default seem to go to /userdata/system)

2. open `about:config` webpage and set `browser.fullscreen.autohide` to `false`

**Comment by batoceragaming** [comment]
1. I am using the latest update of firefox (Just updated). However if I right click an image and save as, there is no save as dialog and download. I also have changed the default download location to "/userdata/downloads" but cannot see any files that has been downloaded.

2. Thanks, finally the fullscreen problem is gone

**Comment by uureel** [comment]
for 1. you'd have to follow with the app's packager @ github.com/srevinsaju/Firefox-Appimage , these here are just installers/compatibilitylayers for batocera
