### ISSUE TITLE
VirtualHere Support?

### ISSUE THREAD

**Issue by geogolem** [uureel/batocera.pro#35]
Is it possible to add "VirtualHere" support to Batocera.pro? Both client and server.. similar to how sunshine/moonlight are available?

https://www.virtualhere.com/

**Comment by uureel** [comment]
nope, none of it seems to work at all in bato

**Comment by geogolem** [comment]
too bad... but i think the better thing would be to add virtualHere support in moonlight.. which some others have suggested here: https://ideas.moonlight-stream.org/posts/211/usb-ip-implementation

this would basically solve the issue for batocera too..

**Comment by uureel** [comment]
would be great if feasible; inputs in linux prove to be rather quite wonky though, and often bork with updates

**Comment by geogolem** [comment]
I think it is more likely that maybe this feature gets implemented in moonlight itself.. but who knows.

https://ideas.moonlight-stream.org/posts/211/usb-ip-implementation
