### ISSUE TITLE
Wine manager suggestion

### ISSUE THREAD

**Issue by Gr3gorywolf** [uureel/batocera.pro#39]
Hello I've developed a application for manage the batocera's default wine and Im wondering if you can put it on this repo, This is my project's repo https://github.com/Gr3gorywolf/batocera_wine_manager

**Comment by uureel** [comment]
sure, added, linked via winemanager.batocera.pro directly to your repo, or you can also add it here

**Comment by Gr3gorywolf** [comment]
Thank you so much!!
