### ISSUE TITLE
Add either a link to the website where the software is from or an explanation of what it is

### ISSUE THREAD

**Issue by DennoCoil** [uureel/batocera.pro#4]
I did not know what at least 1/4 of this software did, so I had to look them up and guess what they were.  

Also, I swear to God the HTML and Markdown on this site is broken.  No matter what, if I try to add text to the Readme, the boxes around the text gets broken and unquoted.  It would probably need a rewrite of the entire file and add proper CSS just to get it rendering correctly.

**Comment by uureel** [comment]
not planned currently

**Comment by udance4ever** [comment]
I definitely agree with @DennoCoil - I sat here Googling “$appname linux” to learn what, for me, 50% of these apps are.

while it would be immensely useful for peeps who install apps, I’m sure the developers and maintainers of the apps would appreciate the links to their websites too.
