### ISSUE TITLE
Pad to key and other windows games options

### ISSUE THREAD

**Issue by isilkin** [uureel/batocera.pro#41]
Feature request. I was wondering if there is a way to add options similar to batocera's default windows game category options when creating shortcuts with lutris and heroic. Basically if one goes into the heroic game category that is generated by batocera.pro padtokey and some other options are not available. Thank you.

**Comment by garbagescow** [comment]
> Feature request. I was wondering if there is a way to add options similar to batocera's default windows game category options when creating shortcuts with lutris and heroic. Basically if one goes into the heroic game category that is generated by batocera.pro padtokey and some other options are not available. Thank you.

Not happening unless you know python and can write the configgens.

**Comment by isilkin** [comment]
Ok, thank you
