### ISSUE TITLE
GPU accelerated web views in Steam causes black screen.

### ISSUE THREAD

**Issue by ChildishhAlbino** [uureel/batocera.pro#42]
## Problem
After enabling GPU accelerated web views, I cannot get the steam UI to load - all I see is a black screen but I can hear sounds so I know the app is running. I set steam to open in big picture mode by default so I can't tell if this only occurs because of that.

Let me know what information I can provide to help debug this.

## Resolution attempts;
- Restarting the machine
- Uninstalling the entire Arch container and reinstalling it, still persisted my login and my settings so please let me know how I can completely purge all that to start fresh. I tried removing the folders under `/userdata/system/.local/share` and get told I can't delete folders because they're not empty. (this happened both manually running the rm -rf command and asking the batocerapro app to uninstall the container)

**Comment by uureel** [comment]
its a steam/linux/nvidia issue, were it not an issue for them you wouldn't have to be turning it on (it'd just be alwayson by default); might maybe work next steam update (since it did work fine before), or it won't and they'll just break something else for a 'change'

**Comment by uureel** [comment]
you should be able to purge steam / restore default settings by `rm -rv ~/.local/share/Steam && rm -rv ~/.steam`

**Comment by ChildishhAlbino** [comment]
Thanks for the help! Will try that and see how that works :D
