### ISSUE TITLE
Feature Request: Close Steam automatically when game launched from ES is exited.

### ISSUE THREAD

**Issue by ChildishhAlbino** [uureel/batocera.pro#43]
## Description
Basically self titled but the user experience with launching Steam games from ES when Flatpak installed worked was quite nice - Steam would open either minimized or silently and when you exited the game you'd be returned to the ES menu.

Is this possible with the arch container version of Steam? If so, can I enable it or have it be provided as an option?

**Comment by garbagescow** [comment]
It's a function of steam, not the launch scripts.  The script default is to launch in bpm which doesn't close out steam. when the game is closed.  You can remove the --gamepadui in the +UPDATE-STEAM-GAMES.sh in the /roms/steam2 so it launches in desktop mode which closes out when done.

**Comment by ChildishhAlbino** [comment]
Thanks for clarifying that for me - will try that and report back.

**Comment by garbagescow** [comment]
Looks like valve removed that function when they updated. i would just use gamepad ui and exit out of the game with the controller then.  Hotkey and the overlay left menu should let you exit.
