### ISSUE TITLE
App request: RomM

### ISSUE THREAD

**Issue by gantoine** [uureel/batocera.pro#45]
Hey ya'll, would you be interested in adding [RomM](https://github.com/rommapp/romm) to the list of apps? I can write the PR for it, just want to know if there's any appetite to having it added. RomM uses MariaDB to store data so I'd need to figure that out (if it's even possible)...

**Comment by uureel** [comment]
hi, cool project, imo fits like a glove, by all means go for it; 

bato doesn't do containers native but you can use `wget batocera.pro/app/batocera-containers` to pull it off, it's an appimaged extension that live-adds podman&docker/compose to batocera (x8664), from there it's pretty straightforward 

of note, there's also a batocera casaos addon available in the repo that has mariadb preinstalled where afair it's running on the default 3006 - so it might be best to just spawn a separate maria instance on different port for romm

**Comment by uureel** [comment]
this repo is scheduled for phase out
