### ISSUE TITLE
ARM64 requests

### ISSUE THREAD

**Issue by rcampbel3** [uureel/batocera.pro#46]
Hi. I have a short list of suggestions for adding as arm64 packages to batocera.pro:

Chromium - obviosuly having a browser would be great!

Moonlight client - I like the official client and not needing to pair from terminal :)

Chiaki - ps4/ps5 remote client - sure some people would want that.

Minecraft Java client - can't seem to get enough and I always keep coming back

Thanks for the great work!

**Comment by garbagescow** [comment]
portmaster has moonlight new now that lets you pair with a gui
