### ISSUE TITLE
Black screen / Kick - from steam + steam big picture mode

### ISSUE THREAD

**Issue by paladinperry** [uureel/batocera.pro#48]
First off, thank you so much for all your hard work ! I actually had this running for 1 day before it stopped working. And was playing DS3 and Elden Ring just fine !

Optplex 3080 SFF
i5 10500
RX6400
16gb UDIMM DDR4 2666mhz
2tb Lexar NVME SSD
Batocera v39

I followed the Xterm command, ran the setup, just perfect !
added all the games I wanted to play via steam app in archlinux folder, perfect !
played plenty of elden ring and DS3 , perfect !

Now today when I try ANY steam app, just a black screen :(

I have uninstalled, reinstalled, ran the steam checker app in archlinux. It just keeps
trying and trying something to do with bootstrapper ? and something sniper 3.0 ?

the test/diagnostic programme shows the steam main page during the check
it shows my account log in and verify then back to the diagnostic. and retrying the thing I mentioned

Just black screen any time I try to run a game directly, or steam , or steam big picture.

Please help me. This is how me and my partner game together lol

**Comment by garbagescow** [comment]
you can delete or move the steam folder  ~/.local/share/Steam and restart and see if works.
