### ISSUE TITLE
PS1 Netplay New Emulator for batocera pro https://www.honmaru.pl/arkadyzja/download

### ISSUE THREAD

**Issue by luizaoooobr** [uureel/batocera.pro#49]
PS1 Eemulator with netplay to batocera pro , please add this 

Download : https://www.honmaru.pl/arkadyzja/download

![image](https://github.com/uureel/batocera.pro/assets/56891889/57939e11-b5b3-4ceb-86a8-162a7db4657e)

**Comment by garbagescow** [comment]
That's a windows version you can install/test via wine.

**Comment by garbagescow** [comment]
That link you provided is windows
