### ISSUE TITLE
Install Gamescope to Steam container?

### ISSUE THREAD

**Issue by ChildishhAlbino** [uureel/batocera.pro#50]
Trying to run a port of a game that doesn't want to fullscreen properly and ProtonDB suggests using `gamescope` to resolve this.

I attempted to use this with no success and it appears this has to be installed separately. Normally I'd follow along with the installation as normal but I'm not sure how I would go about that within the steam container - is that something that can be done and if so - how?

**Comment by garbagescow** [comment]
It's in the container..just have to launch it with one of the terminals.  Not that i ever got it working with steam as it seems to only prefer wayland and not xorg/x11 which is what Batocera uses.

![image](https://github.com/uureel/batocera.pro/assets/162914836/04b372a1-7b60-4b42-8364-afd552c33b24)

**Comment by ChildishhAlbino** [comment]
Hmmm ok - that might be why the game I tried wouldn't boot when I had that in the launch command. Cheers - I'll explore what the options are.
