### ISSUE TITLE
Slower than expected download speeds in Steam

### ISSUE THREAD

**Issue by ChildishhAlbino** [uureel/batocera.pro#51]
On any other PC in my household - I can download steam games significantly faster than when using steam on Batocera - in the order of 5x or greater.

This was also the case when Steam was originally installed the native way. Is there any idea what could be causing slowdown when running in Conty?

**Comment by garbagescow** [comment]
> On any other PC in my household - I can download steam games significantly faster than when using steam on Batocera - in the order of 5x or greater.
> 
> This was also the case when Steam was originally installed the native way. Is there any idea what could be causing slowdown when running in Conty?

your machine  maybe? Did you try on a different one?  Maybe run speed test on it in chrome.

![image](https://github.com/uureel/batocera.pro/assets/162914836/304fd97b-584e-491c-a107-a3a4b8a6f28c)

**Comment by garbagescow** [comment]
> I ran a speed test in Mozilla (installed via flatpak) and got the expected download speeds of ~1Gbps. Downloading games via Wifi on my steam deck still gets at least 10x the download speeds as steam on Batocera atm.
> 
> I don't think it's my machine or my internet.

You checked your download settings in steam settings...closest server, etc?

**Comment by ChildishhAlbino** [comment]
> You checked your download settings in steam settings...closest server, etc?

Yeah all same as the steam deck - my download speed caps out at a max of 50Mbps or sometimes 90Mbps for a split second but it spends the most time in the low 40's or 30's.

**Comment by garbagescow** [comment]
Do you have any games on epic?  Wondering if heroic game launcherdownloads are similar

**Comment by garbagescow** [comment]
and are you running off on a microSD card?

**Comment by ChildishhAlbino** [comment]
> Do you have any games on epic? Wondering if heroic game launcher downloads are similar

I haven't installed Heroic and I don't have experience using it.

> and are you running off on a microSD card?
Running off an m.2 SSD

**Comment by uureel** [comment]
> I ran a speed test in Mozilla (installed via flatpak) and got the expected download speeds of ~1Gbps. Downloading games via Wifi on my steam deck still gets at least 10x the download speeds as steam on Batocera atm.
> 
> I don't think it's my machine or my internet.

how about in container's firefox&/chrome? (unless you meant mozilla from container's flatpak)

**Comment by ChildishhAlbino** [comment]
Ok some further findings - running a speed test in the Steam web browser also records ~1Gpbs. From what I can see this looks to be an issue with the Steam itself.

https://github.com/ValveSoftware/steam-for-linux/issues/10248 This issue details a fix by disabling HTTP2 via `~/.steam/steam/steam_dev.cfg` - I can't seem to find that file from the brief searching I've done - nor can I seem to access the Steam Console tab in the container to disable it that way.

Your thoughts? Tonight I saw download speeds as high as 500 Mbps (for a short while) and as low as 1 Mbps (for a long while).

**Comment by garbagescow** [comment]
more reading suggests you need to create that steam_dev.cfg file in ~/.local/share/Steam/steam_dev.cfg

Some people complain about ipv6 causing issues too..sometimes my bat box loses it's ipv4 address and uses v6 which slows it down till i reboot it.

**Comment by ChildishhAlbino** [comment]
Ok it's quite weird. After changing that setting I can get my near 1Gbps speeds for maybe 30-60 seconds before it begins to nosedive down to 20Mbps for a moment and then it eventually climbs back to 100-200Mbps.

I haven't tried disabling IPV6 on my Batocera machine as I don't know how too 😅 I am getting better performance than I was  and is still useable but it's still 2-3x slower than any other machine.

**Comment by uureel** [comment]
try this
`NET=eth0 && sysctl -w net.ipv6.conf.all.disable_ipv6=1 && sysctl -w net.ipv6.conf.default.disable_ipv6=1 && ifconfig $NET down && ifconfig $NET up`

(or wlan0 etc) 
if works add it to custom.sh

**Comment by uureel** [comment]
@ChildishhAlbino can confirm the issue on my end, looks like steam borked something again with latest updates; no fix, nothing available including _dev.cfg nor any further tinkering yielded any results whatsoever here; up to valve
