### ISSUE TITLE
May I ask how to delete it? 

### ISSUE THREAD

**Issue by shangren-cmd** [uureel/batocera.pro#55]
Currently installed EDGE, unable to use

**Comment by Link-HXX** [comment]
Yes, I also want to know how to uninstall a software. In the application interface, I double-clicked edge, but nothing happened

**Comment by garbagescow** [comment]
delete the launcher in /userdata/roms/ports and the folder for edge in ~/pro

**Comment by dhaern** [comment]
> delete the launcher in /userdata/roms/ports and the folder for edge in ~/pro

This is not true, I deleted everything in ports and /pro and desktop entry in menu://applications/ still visible in F1 menu and show again after every time I delete this.
