### ISSUE TITLE
issue with Sunshine in Batocera with port configuration

### ISSUE THREAD

**Issue by jk7gr** [uureel/batocera.pro#56]
I have 2 Batocera PCs in my network and I want to access them over the internet via Moonlight. 

The logical step for me would be to go to one of the batocera systems and configure the sunshine server to use another family of ports, e.g. 44989. I have managed to have the setup in place with port forwarding and both devices are accessible over internet. 
The problem however is that the Batocera device where I changed the family port is restarting itself every 30 seconds with no obvious reason. The strange thing is that there is no entry in the log that could help me understand what the issue is. 
It seems the appimage has somewhere the port hardcoded but I am not sure. 
I am troubleshooting for some 5 hrs already :) . I am sure is not a simple thing. 

Any ideas?

**Comment by uureel** [comment]
sorry about the 5hrs, there indeed is an autorestart in case sunshine process drops which used to/happens quite so often on my bato box for whatever reason - try ```cd ~/pro/sunshine
./batocera-sunshine --appimage-extract
cd squashfs-root
```
and check 'sunshine-keepalive` and `sunshine-autorestart` there,

you can repack the appimage using appimagetool, or just run the AppRun file there unpacked

**Comment by jk7gr** [comment]
Thanks mate. Seems to be working fine now after doing the necessary modifications to the indicated files.
