### ISSUE TITLE
casaos batocera.pro it doesn't work

### ISSUE THREAD

**Issue by mrmargos** [uureel/batocera.pro#58]
`curl -L casaos.batocera.pro | bash`

it doesn't work

`Downloading split zip files using aria2c...
bash: line 32: ./aria2c: No such file or directory
bash: line 33: ./aria2c: No such file or directory
bash: line 34: ./aria2c: No such file or directory
bash: line 35: ./aria2c: No such file or directory
Failed to download one or more parts of the split zip file. Exiting.
`

**Comment by trashbus99** [comment]
See  note on the main page...repo is deprecated and scheduled for phase out.

**Comment by uureel** [comment]
repo closed
