### ISSUE TITLE
added portproton to the steam container, 

### ISSUE THREAD

**Issue by isilkin** [uureel/batocera.pro#59]
added portproton to the steam container, hulu+netflix added both to the steam container and as standalone apps

_Originally posted by @uureel in https://github.com/uureel/batocera.pro/issues/31#issuecomment-1962420242_
            

Hi, now portproton is officially available on flathub however it does not work with batocera. I think it is because it is looking for a desktop and a save path in a place that does not exist in batocera. Also, did you remove it from batocera pro?. thank you.

**Comment by trashbus99** [comment]
See  note on the main page...repo is deprecated and scheduled for phase out

**Comment by isilkin** [comment]
So sad to it go. Will the repo still be available even though not updated?

**Comment by uureel** [comment]
repo closed
