### ISSUE TITLE
extract-xiso missing .exe

### ISSUE THREAD

**Issue by udance4ever** [uureel/batocera.pro#7]
hi!  I’m new to these scripts - I was trying to figure out why this app doesn’t boot in Applications and it looks like the .exe (referenced in the Launcher created by [extract-xiso.sh](https://github.com/uureel/batocera.pro/blob/main/extract-xiso/extract-xiso.sh)) is missing:

https://github.com/uureel/batocera.pro/blob/b2c7ee2f6dfdae7bfcb361220b6b9b415d6bb6b6/extract-xiso/extract-xiso.sh#L23

**Comment by uureel** [comment]
thx, should be now fixed @ https://github.com/uureel/batocera.pro/commit/644daea756def735a385e255330d3cd56d86257b

**Comment by udance4ever** [comment]
tested - works great now!
